###Configure a variable for the webservice base address
@Northwind.WebApi_HostAddress = https://localhost:5151

POST {{Northwind.WebApi_HostAddress}}/api/customers
Content-Type: application/json

{
  "customerID": "ABDXY",
  "companyName": "ABC Corp",
  "contactName": "John Smith",
  "contactTitle": "Sir",
  "address": "Main Street",
  "city": "New York",
  "region": "NY",
  "postalCode": "90210",
  "country": "USA",
  "phone": "(123) 555-1234"
}

###